### ISSUE TITLE
Restore "at-rule-empty-line-before" when ["first-nested-and-blockless"] option is available

### ISSUE THREAD

**Issue by spaceninja** [saymedia/stylelint-config-saymedia#1]
Currently, we're setting `at-rule-empty-line-before` to `null` because there's no way to get the behavior we want from it. What we'd like to see is the following style:

```css
.foo {
    @include something;
    top: 0;

    @media {
        top: 0;
    }
}

.bar {

    @media {
        top: 0;
    }
}
```

Unfortunately, as the rule is written today, you can either _always_ add a blank line before the first at-rule in a block, or never. There's no way to distinguish between blockless at-rules and block-level at-rules.

There's an open issue for this in the stylelint project — [#2480](https://github.com/stylelint/stylelint/issues/2480) — and once that get fixed, we should restore the rule here in our config.
